# Credit Card Fraud Detection Model

The goal is to create a model to detect fraudulent credit card transactions. The model is built based on an kaggle dataset. \
Link to the data: https://www.kaggle.com/datasets/neharoychoudhury/credit-card-fraud-data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('fraud_data.csv')

In [3]:
df.head()

,trans_date_trans_time,merchant,category,amt,city,state,lat,long,city_pop,job,dob,trans_num,merch_lat,merch_long,is_fraud
0,04-01-2019 00:58,"""Stokes, Christiansen and Sipes""",grocery_net,14.37,Wales,AK,64.7556,-165.6723,145,"""Administrator, education""",09-11-1939,a3806e984cec6ac0096d8184c64ad3a1,65.654142,-164.722603,1
1,04-01-2019 15:06,Predovic Inc,shopping_net,966.11,Wales,AK,64.7556,-165.6723,145,"""Administrator, education""",09-11-1939,a59185fe1b9ccf21323f581d7477573f,65.468863,-165.473127,1
2,04-01-2019 22:37,Wisozk and Sons,misc_pos,49.61,Wales,AK,64.7556,-165.6723,145,"""Administrator, education""",09-11-1939,86ba3a888b42cd3925881fa34177b4e0,65.347667,-165.914542,1
3,04-01-2019 23:06,Murray-Smitham,grocery_pos,295.26,Wales,AK,64.7556,-165.6723,145,"""Administrator, education""",09-11-1939,3a068fe1d856f0ecedbed33e4b5f4496,64.445035,-166.080207,1
4,04-01-2019 23:59,Friesen Lt,health_fitness,18.17,Wales,AK,64.7556,-165.6723,145,"""Administrator, education""",09-11-1939,891cdd1191028759dc20dc224347a0ff,65.447094,-165.446843,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14446 entries, 0 to 14445
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   trans_date_trans_time  14446 non-null  object
 1   merchant               14446 non-null  object
 2   category               14446 non-null  object
 3   amt                    14446 non-null  float64
 4   city                   14446 non-null  object
 5   state                  14446 non-null  object
 6   lat                    14446 non-null  float64
 7   long                   14446 non-null  float64
 8   city_pop               14446 non-null  int64
 9   job                    14446 non-null  object
 10  dob                    14446 non-null  object
 11  trans_num              14446 non-null  object
 12  merch_lat              14446 non-null  float64
 13  merch_long             14446 non-null  float64
 14  is_fraud               14446 non-null  object
dtypes: float64(5), int64(1), object(9)
memory usage: 1.7+ MB

## First Observation
There are no missing values in the dataset

# EDA (Univariate, Bivariate)

## is_fraud

In [5]:
df.is_fraud.value_counts()

is_fraud
0                         12600
1                          1844
1"2020-12-24 16:56:24"        1
0"2019-01-01 00:00:44"        1
Name: count, dtype: int64

**Observation:**
- There are two values in the is_fraud column that are timestamps -> delete the two rows
- The clumn is object type -> convert to int

In [6]:
# get index of the two defect rows
df.loc[~(df.is_fraud.isin(['0','1']))]

,trans_date_trans_time,merchant,category,amt,city,state,lat,long,city_pop,job,dob,trans_num,merch_lat,merch_long,is_fraud
1781,11-12-2020 23:19,Thompson-Gleason,health_fitness,19.45,Lakeport,CA,39.0470,-122.9328,11256,Podiatrist,18-10-1972,bfde75d978bb9905a4a8c87440692a4c,39.251880,-122.490946,"1""2020-12-24 16:56:24"""
7780,31-12-2020 23:59,Breitenberg LLC,travel,7.99,Mesa,ID,44.6255,-116.4493,129,Cartographer,15-12-1965,14392d723bb7737606b2700ac791b7aa,44.470525,-117.080888,"0""2019-01-01 00:00:44"""

In [7]:
# drop the rows
df = df.drop(index=[1781,7780])
# convert the column to int 
df['is_fraud'] = df.is_fraud.astype('int')

**Conclusion:** \
There are  ~14.5% fraudulent transactions in the dataset